[Application]
WindowWidth = 780
WindowHeight = 917
LastCheckedVersion = 'v0.18.1'
LastLaunchedVersion = 'v0.18.1'
EnableSystemTray = true
CloseToSystemTray = false
StartupPage = 'Albums'
SettingsTab = 'Playback'
AllowMultiInstance = false
MaxImageCacheSizeMB = 50
SavePlayQueue = true
SaveQueueToServer = false
DefaultPlaylistID = ''
AddToPlaylistSkipDuplicates = false
ShowTrackChangeNotification = false
EnableLrcLib = true
CustomLrcLibUrl = ''
EnablePasswordStorage = true
SkipSSLVerify = false
EnqueueBatchSize = 100
Language = 'fr'
DisableDPIDetection = false
EnableAutoUpdateChecker = true
RequestTimeoutSeconds = 15
EnableOSMediaPlayerAPIs = true
FontNormalTTF = ''
FontBoldTTF = ''
UIScaleSize = 'Normal'

[[Servers]]
ServerType = 'Subsonic'
Hostname = 'https://music.kione.ovh'
AltHostname = ''
Username = 'Samuel'
LegacyAuth = false
ID = '0e7b7de8-f8f5-46d3-bb5b-939ab98221a1'
Nickname = 'Kione'
Default = true
SelectedLibrary = ''

[AlbumPage]
TracklistColumns = ['Artist', 'Time', 'Plays', 'Favorite', 'Rating']

[AlbumsPage]
SortOrder = 'Recently Added'
ShowYears = false
ShuffleMode = 'Tracks'
PlayInOrder = false

[ArtistPage]
InitialView = 'Discography'
DiscographySort = ''
TracklistColumns = ['Album', 'Time', 'Plays', 'Favorite', 'Rating']

[ArtistsPage]
SortOrder = 'Name (A-Z)'

[FavoritesPage]
InitialView = 'Albums'
TracklistColumns = ['Album', 'Time', 'Plays']
ShowAlbumYears = false

[GridView]
CardSize = 260.0

[PlaylistPage]
TracklistColumns = ['Album', 'Time', 'Plays']

[PlaylistsPage]
InitialView = 'List'

[TracksPage]
TracklistColumns = ['Album', 'Time', 'Plays']

[NowPlayingConfig]
InitialView = 'Play Queue'

[Playback]
Autoplay = false
RepeatMode = 'None'
UseWaveformSeekbar = true

[LocalPlayback]
AudioDeviceName = 'auto'
AudioExclusive = false
InMemoryCacheSizeMB = 30
Volume = 100
EqualizerEnabled = false
EqualizerPreamp = 0.0
GraphicEqualizerBands = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[Scrobbling]
Enabled = true
ThresholdTimeSeconds = 240
ThresholdPercent = 50

[ReplayGain]
Mode = 'no'
PreampGainDB = 0.0
PreventClipping = true

[Transcoding]
ForceRawFile = false
RequestTranscode = false
Codec = 'opus'
MaxBitRateKBPS = 160

[Theme]
ThemeFile = 'catppuccin-modified.toml'
Appearance = 'Light'

[PeakMeter]
WindowHeight = 100
WindowWidth = 375
