#!/usr/bin/env bash

pkill --euid "$USER" --signal SIGINT wf-recorder && exit

DefaultSaveDir='/home/samuel/GIFs'
TmpPathPrefix='/tmp/gif-record'
TmpRecordPath=$TmpPathPrefix'-cap.mp4'
TmpPalettePath=$TmpPathPrefix'-palette.png'

OnExit() {
    [[ -f $TmpRecordPath ]] && rm -f "$TmpRecordPath"
    [[ -f $TmpPalettePath ]] && rm -f "$TmpPalettePath"
}
trap OnExit EXIT

umask 177

Coords=$(slurp) || exit

timeout 600 wf-recorder -g "$Coords" -r 30 -f "$TmpRecordPath" || exit

SavePath=$(zenity --file-selection --save --confirm-overwrite --file-filter=*.gif --filename="$DefaultSaveDir"'/.gif') || exit

[[ $SavePath =~ \.gif$ ]] || SavePath+='.gif'

# Génération palette avec filtre complet et stats_mode=full
ffmpeg -i "$TmpRecordPath" -vf "fps=15,scale=iw:ih:flags=lanczos,palettegen=stats_mode=full" "$TmpPalettePath" -y || exit

umask 022

# Conversion vidéo en GIF avec palette et dithering Bayer
ffmpeg -i "$TmpRecordPath" -i "$TmpPalettePath" -filter_complex "fps=15,scale=iw:ih:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer" "$SavePath" -y || exit
